server:
  port: ${SERVER_PORT}
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: authentication-service
              uri: lb://authentication-service
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

eureka:
  client:
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance-id}:${random.value}
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL} #Servidor de Eureka
