server:
  port: ${SERVER_PORT}
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: authentication-service
              uri: lb://authentication-service
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/cust/**
              filters:
                - StripPrefix=1
            - id: employee-service
              uri: lb://employee-service
              predicates:
                - Path=/empl/**
              filters:
                - StripPrefix=1
            - id: inventory-matter-service
              uri: lb://inventory-matter-service
              predicates:
                - Path=/inve/**
              filters:
                - StripPrefix=1
            - id: payment-gateway-service
              uri: lb://payment-gateway-service
              predicates:
                - Path=/paym/**
              filters:
                - StripPrefix=1
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/prod/**
              filters:
                - StripPrefix=1

eureka:
  client:
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance-id}:${random.value}
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL} #Servidor de Eureka
