# Configuraci칩n para DESARROLLO/PRUEBAS con H2 Database
# Usa este archivo cuando NO tengas PostgreSQL instalado

server:
  port: 8098

spring:
  application:
    name: customer-service

  # H2 Database en memoria (NO requiere instalaci칩n)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # Configuraci칩n JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: create-drop  # Crea las tablas autom치ticamente
    show-sql: true  # Muestra las consultas SQL en consola
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true  # Formatea el SQL para mejor lectura

  # Consola H2 (para ver la base de datos en el navegador)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

# Desactivar Eureka para pruebas locales
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

# Logging
logging:
  level:
    com.content.customer_service: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

