server:
  port: ${SERVER_PORT}
spring:
  application:
    name: trabajador-servicio

eureka:
  client:
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance-id}:${random.value}
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL} #Servidor de Eureka